export const QUESTION_TYPES = {
	TEXT: "text",
	LONG_TEXT: "longText",
	YES_NO: "yesNo",
	MULTIPLE_CHOICE: "multipleChoice",
	SINGLE_CHOICE: "singleChoice",
	RATING: "rating",
	DROPDOWN: "dropdown",
	LIKERT: "likert",
	SLIDER: "slider",
	DEMOGRAPHIC: "demographic",
	FILE_UPLOAD: "fileUpload",
	SECTION: "section",
	AUTHORIZATION: "authorization",
};
