export const questions = [
  {
    id: "aboutUs",
    title: "About Us",
    type: "richText",
    required: false,
    info: true,
    instructions: "Provide a short overview of your company, including your core business areas and expertise.",
    placeholder: "Company background, expertise, and core business areas...",
    minHeight: 300,
    maxLength: 2000,
  },
  {
    id: "mission",
    title: "Mission Statement", 
    type: "richText",
    required: false,
    info: true,
    instructions: "Define your company's purpose and primary objectives.",
    placeholder: "Describe your company's mission...",
    minHeight: 300,
    maxLength: 2000,
  },
  {
    id: "vision",
    title: "Vision Statement",
    type: "richText", 
    required: false,
    info: true,
    instructions: "Describe your company's aspirations and future goals.",
    placeholder: "Describe your company's vision...",
    minHeight: 300,
    maxLength: 2000,
  },
  {
    id: "competitiveAdvantage",
    title: "Competitive Advantage",
    type: "richText",
    required: false,
    info: true,
    instructions: "Describe what sets your company apart from competitors and your unique value proposition.",
    placeholder: "Describe your company's competitive advantages...",
    minHeight: 300,
    maxLength: 2000,
  },
  {
    id: "keyCapabilities",
    title: "Key Capabilities",
    type: "sortableList",
    required: false,
    info: true,
    instructions: "List your company's key capabilities and core competencies.",
    placeholder: "Capability...",
    minHeight: 300,
    maxLength: 100,
  }
];